export default {
  // Common strings
  common: {
    back: "Zpět",
    save: "Uložit",
    cancel: "Zrušit",
    confirm: "Potvrdit",
    yes: "Ano",
    no: "Ne",
    loading: "Načítání...",
    error: "Chyba",
    success: "Úspěch",
    warning: "Varování",
    add: "Přidat",
    remove: "Odstranit",
    edit: "Upravit",
    delete: "Smazat",
    reset: "Resetovat",
    clear: "Vyčistit",
    close: "Zavřít",
    actions: "Akce",
    search: "Hledat",
    filter: "Filtrovat",
    sort: "Seřadit",
    show: "Zobrazit",
    hide: "Skrýt",
    continue: "Pokračovat",
  },

  // Headers and menu
  header: {
    title: "Volejbalový turnaj",
    newTournament: "Nový turnaj",
    games: "Zápasy",
    results: "Výsledky",
    history: "Historie",
    playerRatings: "Hodnocení hráčů",
    settings: "Nastavení",
    dataManagement: "Správa dat",
    rules: "Pravidla",
    darkTheme: "Tmavý motiv",
    lightTheme: "Světlý motiv",
  },

  // Tournament format
  tournamentFormat: {
    fullTeams: "kompletní týmy",
    triples: "trojice",
    doubles: "dvojice",
  },

  // Player input
  playerInput: {
    startTournament: "Začít turnaj",
    playerCount: "Počet účastníků",
    playerCountError: "Počet účastníků musí být mezi 12 a 18",
    playerNamePlaceholder: "Jméno hráče",
    playerNameError: "Všechna jména musí být vyplněna",
    uniqueNameError: "Jména musí být jedinečná",
  },

  // Game board
  gameBoard: {
    currentGame: "Aktuální hra",
    switchSides: "Vyměnit strany",
    switchBack: "Vrátit strany",
    changeComposition: "Změnit složení",
    gameTo: "Hra do",
    pointsWithDifference: "bodů s minimálním rozdílem",
    points: "bodů",
    gameFinished: "Hra skončila! Klikněte na tlačítko \"Dokončit hru\" pro pokračování.",
    gameFinishError: "Hra nemůže být ukončena:",
    needToReachScore: "je potřeba dosáhnout {score} bodů.",
    needPointDifference: "bodový rozdíl musí být alespoň {diff} bodů.",
    matchPrediction: "Předpověď zápasu",
    winChances: "Šance na výhru:",
    versus: "PROTI",
    matchCharacteristics: "Charakteristiky zápasu:",
    closeMatch: "Vyrovnaný zápas",
    hasAdvantage: "{team} má výhodu",
    swipeModeEnabled: "Režim přejetí aktivován",
    enableSwipeMode: "Aktivovat režim přejetí",
    swipeHint: "Přejeďte vlevo/vpravo pro změnu skóre",
    gameTime: "Čas hry:",
    start: "Start",
    pause: "Pauza",
    finishGame: "Dokončit hru",
    resetScore: "Resetovat skóre",
    scoreHistory: "Historie skóre",
    show: "Zobrazit",
    hide: "Skrýt",
    set: "Set",
    inProgress: "(probíhá)",
    completed: "(dokončeno)",
    time: "Čas:",
    finalScore: "Konečné skóre",
    prediction: "Předpověď",
  },

  // Game list
  gameList: {
    scheduleTitle: "Rozpis zápasů",
    sortByRound: "Podle kola",
    sortByDate: "Podle data",
    sortByScore: "Podle skóre",
    sortByTeam: "Podle týmu",
    filter: "Filtr",
    filterByTeamOrPlayer: "Filtrovat podle týmu nebo hráče",
    filterPlaceholder: "Zadejte jméno týmu nebo hráče",
    resetFilter: "Resetovat",
    nextGame: "Další zápas",
    round: "Kolo",
    lineup: "Sestava",
    restingTeams: "Odpočívají:",
    startGame: "Začít zápas",
    noSchedule: "Rozpis ještě není vytvořen.",
    scheduleMessage: "Po zahájení turnaje se zde objeví úplný rozpis zápasů",
    totalGames: "Celkem zápasů:",
    game: "Zápas",
    upcoming: "Nadcházející",
    notPlayed: "Nehráno",
    points: "Body:",
    returnToGame: "Návrat do hry",
  },

  // Results table
  resultsTable: {
    title: "Konečné výsledky",
    noResults: "Zatím žádné výsledky.",
    place: "Místo",
    team: "Tým",
    points: "Body",
    wins: "Výhry",
    losses: "Prohry",
    gamesPlayed: "Odehráno zápasů",
    scoreDiff: "Rozdíl bodů",
    setsWon: "Vyhráno setů",
    setsLost: "Prohráno setů",
    showDetails: "Zobrazit detaily",
    hideDetails: "Skrýt detaily",
  },

  // Tournament history
  historyView: {
    title: "Historie turnajů",
    noHistory: "Zatím žádné dokončené turnaje.",
    tournament: "Turnaj",
    teams: "Týmy:",
    games: "Zápasy:",
    results: "Výsledky:",
    searchPlaceholder: "Vyhledat turnaje...",
    filterBy: "Filtrovat podle:",
    all: "Vše",
    sortBy: "Seřadit podle:",
    date: "Datum",
    participants: "Účastníci",
    duration: "Trvání",
    winner: "Vítěz",
    format: "Formát",
    showDetails: "Zobrazit detaily",
    hideDetails: "Skrýt detaily",
    gameResults: "Výsledky zápasů",
    finalResults: "Konečné výsledky",
    noGames: "Žádné zaznamenané zápasy",
    playedOn: "Hráno",
    players: "hráčů",
    totalGames: "zápasů",
    deleteTournament: "Smazat turnaj",
    confirmDelete: "Opravdu chcete smazat tento turnaj?",
    deleteWarning: "Tuto akci nelze vrátit zpět!",
    tournamentsCount: "turnajů",
    noHistoryDesc: "Začněte první turnaj, abyste jej zde viděli po dokončení",
    noSearchResults: "Turnaje nenalezeny",
    tryDifferentSearch: "Zkuste změnit vyhledávací dotaz",
    sortNewest: "Nejnovější první",
    sortOldest: "Nejstarší první",
    sortByTeams: "Podle počtu týmů",
    sortByGames: "Podle počtu zápasů",
  },

  // Settings
  settings: {
    title: "Nastavení turnaje",
    basicSettings: "Základní nastavení",
    useTeamBalancing: "Použít vyvážení týmů",
    balancingDescription: "Týmy budou tvořeny na základě hodnocení hráčů",
    showTeamRatings: "Zobrazit hodnocení týmů",
    ratingsDescription: "Zobrazit průměrné hodnocení týmů během hry",
    showPredictions: "Zobrazit předpovědi",
    predictionsDescription: "Zobrazit pravděpodobnost výhry týmu před zápasem",
    minPointDifference: "Minimální bodový rozdíl pro vítězství",
    diffDescription: "Požadovaná výhoda pro ukončení hry",
    roundDuration: "Délka kola pro dvojice (minuty)",
    durationDescription: "Čas pro jedno kolo ve formátu dvojic",
    gameSettingsByFormat: "Nastavení hry podle formátu",
    fullTeams: "Kompletní týmy",
    maxScore: "Maximální skóre:",
    formatDescription: "Formát pro {count} hráčů",
    triples: "Trojice",
    doubles: "Dvojice",
    scoringSettings: "Nastavení bodování",
    forWin: "Za výhru",
    forLoseGood: "Za prohru (10+ bodů)",
    forLoseBad: "Za prohru (méně než 10 bodů)",
    scoringSystem: "Systém bodování",
    useSetBasedForFull: "Použít bodování podle setů pro kompletní týmy",
    setBasedDescription: "1 bod za vyhraný set (místo tradičního systému 3-2-1 bodů)",
    saveSettings: "Uložit nastavení",
  },

  // Player ratings
  playersRating: {
    title: "Hodnocení hráčů",
    searchPlaceholder: "Hledat hráče...",
    player: "Hráč",
    rating: "Hodnocení",
    games: "Zápasy",
    wins: "Výhry",
    winRate: "ÚV%",
    actions: "Akce",
    detailedStats: "Podrobné statistiky",
    noRatings: "Zatím žádná data o hodnocení hráčů",
    noRatingsMessage: "Uspořádejte několik turnajů pro vytvoření hodnocení",
  },

  // Player stats
  playerStats: {
    loading: "Načítání statistik...",
    notFound: "Statistiky nenalezeny",
    rating: "Hodnocení:",
    games: "Zápasy:",
    wins: "Výhry:",
    winRate: "Úspěšnost výher:",
    overview: "Přehled",
    gamesHistory: "Historie zápasů",
    partners: "Partneři",
    gameStats: "Statistiky zápasů",
    totalGames: "Celkem zápasů:",
    victories: "Vítězství:",
    winPercent: "Procento výher:",
    totalPoints: "Celkem bodů:",
    pointsPerGame: "Bodů za zápas (průměr):",
    indicators: "Ukazatelé",
    currentRating: "Aktuální hodnocení:",
    totalScored: "Celkem skórováno:",
    avgScorePerGame: "Průměrné skóre za zápas:",
    lastActivity: "Poslední aktivita:",
    compatibility: "Kompatibilita",
    uniqueTeammates: "Jedineční spoluhráči:",
    uniqueOpponents: "Jedineční soupeři:",
    lastGames: "Nedávné zápasy",
    date: "Datum",
    team: "Tým",
    opponents: "Soupeři",
    score: "Skóre",
    result: "Výsledek",
    victory: "vítězství",
    defeat: "porážka",
    points: "Body",
    history: "Historie zápasů",
    historyNotFound: "Historie zápasů nenalezena",
    teammates: "Spoluhráči",
    teammatesNotFound: "Žádní spoluhráči nenalezeni",
    opponents: "Soupeři",
    opponentsNotFound: "Žádní soupeři nenalezeni",
  },

  // Data management
  dataManagement: {
    title: "Správa dat",
    exportData: "Export dat",
    exportDescription: "Uložit všechna data turnaje, historii a hodnocení hráčů do souboru JSON pro zálohu nebo přenos na jiné zařízení.",
    exportButton: "Exportovat data",
    importData: "Import dat",
    importDescription: "Nahrát dříve exportovaný soubor JSON k obnovení dat turnaje, historie a hodnocení hráčů.",
    importButton: "Importovat data",
    dataClear: "Vyčištění dat",
    clearDescription: "Smazat aktuální turnaj. Tuto akci nelze vrátit zpět.",
    clearButton: "Vyčistit aktuální turnaj",
    clearConfirm: "Jste si jistí? Tuto akci nelze vrátit zpět.",
    exportSuccess: "Data byla úspěšně exportována",
    exportError: "Chyba při exportu dat",
    importSuccess: "Data byla úspěšně importována",
    importError: "Chyba při importu dat",
    fileError: "Chyba při zpracování souboru",
    readError: "Chyba při čtení souboru",
  },

  // Notifications
  notifications: {
    tournamentCreated: "Turnaj vytvořen",
    teamsFormedMessage: "Týmy vytvořeny a rozpis připraven ({games} zápasů). Formát: {format}",
    newTournament: "Nový turnaj",
    newTournamentMessage: "Předchozí turnaj vyčištěn, připraven začít nový.",
    gameStarted: "Zápas začal",
    gameStartedMessage: "Kolo {round} začíná. Tým {team1} proti {team2}",
    gameFinished: "Zápas ukončen",
    gameFinishedMessage: "Kolo {round} dokončeno s výsledkem {score1}:{score2}.",
    tournamentFinished: "Turnaj dokončen",
    tournamentFinishedMessage: "Všechny zápasy odehrány! Zkontrolujte tabulku konečných výsledků.",
    settingsSaved: "Nastavení uloženo",
    settingsSavedMessage: "Změny nastavení aplikovány na turnaj.",
    dataExport: "Export dat",
    dataExportSuccess: "Data úspěšně exportována do souboru.",
    exportError: "Chyba exportu",
    exportErrorMessage: "Chyba při exportu dat.",
    importError: "Chyba importu",
    fileNotSelected: "Nebyl vybrán žádný soubor.",
    dataImport: "Import dat",
    dataImportSuccess: "Data úspěšně importována.",
    importError: "Chyba importu",
    importErrorMessage: "Chyba při importu dat.",
    formatError: "Soubor obsahuje neplatný formát dat.",
    readError: "Nepodařilo se přečíst soubor.",
  },

  // Reset tournament
  resetTournament: {
    title: "Resetovat aktuální turnaj?",
    message: "Již máte aktivní turnaj. Všechna data budou ztracena! Jste si jistí, že ho chcete resetovat",
    andStartNew: "a začít nový",
    cancel: "Zrušit",
    reset: "Resetovat turnaj",
    resetAndStart: "Resetovat a začít nový",
  },

  // Rules
  rules: {
    title: "Pravidla turnaje",
    basicPrinciples: "Základní principy",
    flexibility: "Flexibilita formátu:",
    flexibilityDesc: "Podpora různých formátů týmů — kompletní týmy (6-7 lidí), trojice nebo dvojice.",
    randomization: "Náhodné složení týmů:",
    randomizationDesc: "Složení týmů se mění před každým kolem pro různorodost a vyváženost.",
    fairness: "Spravedlnost:",
    fairnessDesc: "Stejný herní čas pro všechny účastníky.",
    transparency: "Transparentnost:",
    transparencyDesc: "Přístupná historie výsledků a statistik.",
    formats: "Formáty turnaje",
    fullTeamsFormat: "Kompletní týmy (12-14 účastníků):",
    fullTeamsDesc1: "Dva týmy po 6-7 lidech",
    fullTeamsDesc2: "Hra do 25 bodů s minimálním rozdílem 2 bodů",
    triplesFormat: "Formát trojic (15 nebo 18 účastníků):",
    triplesDesc1: "5-6 trojic (3 lidé v každé)",
    triplesDesc2: "Hra do 15 bodů",
    triplesDesc3: "Jedna trojice odpočívá v každém kole",
    doublesFormat: "Formát dvojic (16-17 účastníků):",
    doublesDesc1: "8 dvojic (2 lidé v každé)",
    doublesDesc2: "10minutové zápasy do 25 bodů s rozdílem 2 bodů",
    doublesDesc3: "Dvě dvojice odpočívají v každém kole",
    scoring: "Bodování",
    scoringDesc: "Body jsou udělovány podle jednotného systému:",
    forWin: "3 body: za vítězství",
    forLoseGood: "2 body: za porážku, pokud tým získal 10 nebo více bodů",
    forLoseBad: "1 bod: za porážku, pokud tým získal méně než 10 bodů",
    close: "Zavřít",
  },

  // Import Modal
  importModal: {
    title: "Import dat",
    selectFile: "Vyberte soubor JSON k importu:",
    cancel: "Zrušit",
    importing: "Importuje se...",
    import: "Importovat",
  },

  // Team mode selection
  teamMode: {
    selectMode: "Výběr režimu vytváření týmů",
    playersCount: "Počet hráčů",
    description: "Vyberte způsob formování týmů pro turnaj",
    automatic: "Automatický",
    manual: "Ruční",
    autoFeature1: "Rychlé vytvoření týmů",
    autoFeature2: "Vyvážení podle hodnocení",
    autoFeature3: "Optimální rozdělení",
    manualFeature1: "Plná kontrola složení",
    manualFeature2: "Výběr partnerů",
    manualFeature3: "Zohlednění osobních preferencí",
    autoDescription: "Týmy budou vytvořeny automaticky s ohledem na hodnocení hráčů pro maximální vyvážení.",
    manualDescription: "Budete moci sami rozdělit hráče do týmů pomocí pohodlného rozhraní drag & drop.",
  },

  // Manual team building
  manualTeam: {
    buildTeams: "Vytváření týmů",
    instructions: "Instrukce",
    dragAndDrop: "Přetáhněte hráče mezi zónami nebo použijte tlačítka pro přesunutí",
    autoDistribute: "Auto-rozdělení",
    clearAll: "Vyčistit vše",
    unassigned: "Nepřiřazení",
    team1: "Tým 1",
    team2: "Tým 2",
    players: "hráčů",
    dropPlayersHere: "Přetáhněte hráče sem",
    allPlayersAssigned: "Všichni hráči jsou přiřazeni",
    moveToTeam1: "Přesunout do týmu 1",
    moveToTeam2: "Přesunout do týmu 2",
    moveToUnassigned: "Odebrat z týmu",
    teamStatus: "Stav týmů",
    allPlayersAssignedStatus: "Všichni hráči jsou přiřazeni",
    bothTeamsHavePlayers: "Oba týmy mají hráče",
    createTeams: "Vytvořit týmy",
    teamFull: "{teamName} je plný ({maxSize}/{maxSize}). Zkuste jiný tým.",
    teamFullSuggestion: "{teamName} je plný! Zkuste přidat hráče do {alternativeTeam}.",
    teamComplete: "Tým je kompletní",
    teamProgress: "Vyplněno {progress}%",
  },

  // Team composition changes
  teamComposition: {
    title: "Změna složení týmů",
    beforeSetDescription: "Upravte složení týmů před {set} setem",
    shuffle: "Promíchat",
    swapTeams: "Vyměnit týmy",
    status: "Stav",
    compositionChanged: "Složení týmů bylo změněno",
    noChanges: "Žádné změny",
    teamSizes: "Velikosti týmů",
    applyChanges: "Použít změny",
    moveToTeam1: "Přesunout do týmu 1",
    moveToTeam2: "Přesunout do týmu 2",
  },
};