export default {
  // Общие строки
  common: {
    back: "Назад",
    save: "Сохранить",
    cancel: "Отмена",
    confirm: "Подтвердить",
    yes: "Да",
    no: "Нет",
    loading: "Загрузка...",
    error: "Ошибка",
    success: "Успешно",
    warning: "Предупреждение",
    add: "Добавить",
    remove: "Удалить",
    edit: "Редактировать",
    delete: "Удалить",
    reset: "Сбросить",
    clear: "Очистить",
    close: "Закрыть",
    actions: "Действия",
    search: "Поиск",
    filter: "Фильтр",
    sort: "Сортировка",
    show: "Показать",
    hide: "Скрыть",
    continue: "Продолжить",
  },

  // Заголовки и меню
  header: {
    title: "Volleyball Турнир",
    newTournament: "Новый турнир",
    games: "Игры",
    results: "Результаты",
    history: "История",
    playerRatings: "Рейтинг игроков",
    settings: "Настройки",
    dataManagement: "Управление данными",
    rules: "Правила",
    darkTheme: "Тёмная тема",
    lightTheme: "Светлая тема",
  },

  // Формат турнира
  tournamentFormat: {
    fullTeams: "полные команды",
    triples: "тройки",
    doubles: "двойки",
  },

  // Ввод игроков
  playerInput: {
    startTournament: "Начать турнир",
    playerCount: "Количество участников",
    playerCountError: "Количество участников должно быть от 8 до 18",
    playerNamePlaceholder: "Имя игрока",
    playerNameError: "Все имена должны быть заполнены",
    uniqueNameError: "Имена должны быть уникальными",
  },

  // Игровое поле
  gameBoard: {
    currentGame: "Текущая игра",
    switchSides: "Поменять местами",
    switchBack: "Вернуть",
    changeComposition: "Изменить состав",
    gameTo: "Игра до",
    pointsWithDifference: "очков с минимальной разницей в",
    points: "очка",
    gameFinished: "Игра завершена! Нажмите кнопку \"Завершить игру\" для продолжения.",
    gameFinishError: "Игра не может быть завершена:",
    needToReachScore: "необходимо набрать {score} очков.",
    needPointDifference: "разница в счете должна быть не менее {diff} очков.",
    matchPrediction: "Прогноз матча",
    winChances: "Шансы на победу:",
    versus: "VS",
    matchCharacteristics: "Характеристика матча:",
    closeMatch: "Близкая игра",
    hasAdvantage: "{team} имеет преимущество",
    swipeModeEnabled: "Режим свайпов включен",
    enableSwipeMode: "Включить режим свайпов",
    swipeHint: "Свайпните влево/вправо для изменения счёта",
    gameTime: "Время игры:",
    start: "Старт",
    pause: "Пауза",
    finishGame: "Завершить игру",
    resetScore: "Сбросить счёт",
    scoreHistory: "История счёта",
    show: "Показать",
    hide: "Скрыть",
    set: "Set",
    inProgress: "(играется)",
    completed: "(завершен)",
    time: "Время:",
    finalScore: "Итоговый счёт",
    prediction: "Предсказание",
  },

  // Список игр
  gameList: {
    scheduleTitle: "Расписание игр",
    sortByRound: "По раунду",
    sortByDate: "По дате",
    sortByScore: "По счёту",
    sortByTeam: "По команде",
    filter: "Фильтр",
    filterByTeamOrPlayer: "Фильтр по команде или игроку",
    filterPlaceholder: "Введите название команды или имя игрока",
    resetFilter: "Сбросить",
    nextGame: "Следующая игра",
    round: "Раунд",
    lineup: "Состав",
    restingTeams: "Отдыхают:",
    startGame: "Начать игру",
    noSchedule: "Расписание пока не сформировано.",
    scheduleMessage: "После старта турнира здесь появится полное расписание игр",
    totalGames: "Всего игр:",
    game: "Игра",
    upcoming: "Предстоит",
    notPlayed: "Не сыграна",
    points: "Очки:",
    returnToGame: "Вернуться к игре",
  },

  // Таблица результатов
  resultsTable: {
    title: "Итоговые результаты",
    noResults: "Пока нет результатов.",
    place: "Место",
    team: "Команда",
    points: "Очки",
    wins: "Победы",
    losses: "Поражения",
    gamesPlayed: "Игр сыграно",
    scoreDiff: "Разность очков",
    setsWon: "Сетов выиграно",
    setsLost: "Сетов проиграно",
    showDetails: "Показать детали",
    hideDetails: "Скрыть детали",
  },

  // История турниров
  historyView: {
    title: "История турниров",
    noHistory: "Пока нет завершённых турниров.",
    tournament: "Турнир",
    teams: "Команд:",
    games: "Игр:",
    results: "Результаты:",
    searchPlaceholder: "Поиск турниров...",
    filterBy: "Фильтр по:",
    all: "Все",
    sortBy: "Сортировка:",
    date: "Дата",
    participants: "Участники",
    duration: "Длительность",
    winner: "Победитель",
    format: "Формат",
    showDetails: "Показать детали",
    hideDetails: "Скрыть детали",
    gameResults: "Результаты игр",
    finalResults: "Итоговые результаты",
    noGames: "Нет записанных игр",
    playedOn: "Сыграно",
    players: "игроков",
    totalGames: "игр",
    deleteTournament: "Удалить турнир",
    confirmDelete: "Вы уверены, что хотите удалить этот турнир?",
    deleteWarning: "Это действие нельзя отменить!",
    tournamentsCount: "турниров",
    noHistoryDesc: "Начните первый турнир, чтобы увидеть его здесь после завершения",
    noSearchResults: "Турниры не найдены",
    tryDifferentSearch: "Попробуйте изменить поисковый запрос",
    sortNewest: "Сначала новые",
    sortOldest: "Сначала старые",
    sortByTeams: "По количеству команд",
    sortByGames: "По количеству игр",
  },

  // Настройки
  settings: {
    title: "Настройки турнира",
    basicSettings: "Основные настройки",
    useTeamBalancing: "Использовать балансировку команд",
    balancingDescription: "Команды будут формироваться с учётом рейтинга игроков",
    showTeamRatings: "Показывать рейтинг команд",
    ratingsDescription: "Отображать средний рейтинг команд во время игры",
    showPredictions: "Показывать прогнозы",
    predictionsDescription: "Отображать вероятность победы команд перед игрой",
    minPointDifference: "Минимальная разница в очках для победы",
    diffDescription: "Необходимое преимущество для завершения игры",
    roundDuration: "Длительность раунда для двоек (минут)",
    durationDescription: "Время на один раунд в формате двоек",
    gameSettingsByFormat: "Настройки игры по форматам",
    fullTeams: "Полные команды",
    maxScore: "Макс. счёт:",
    formatDescription: "Формат для {count} игроков",
    triples: "Тройки",
    doubles: "Двойки",
    scoringSettings: "Начисление очков",
    forWin: "За победу",
    forLoseGood: "За поражение (10+ очков)",
    forLoseBad: "За поражение (менее 10 очков)",
    scoringSystem: "Система начисления очков",
    useSetBasedForFull: "Использовать очки за сеты для полных команд",
    setBasedDescription: "1 очко за выигранный сет (вместо традиционной системы 3-2-1 очка)",
    saveSettings: "Сохранить настройки",
  },

  // Рейтинг игроков
  playersRating: {
    title: "Рейтинг игроков",
    searchPlaceholder: "Поиск игрока...",
    player: "Игрок",
    rating: "Рейтинг",
    games: "Игры",
    wins: "Победы",
    winRate: "WR%",
    actions: "Действия",
    detailedStats: "Подробная статистика",
    noRatings: "Ещё нет данных о рейтингах игроков",
    noRatingsMessage: "Проведите несколько турниров для формирования рейтинга",
  },

  // Статистика игрока
  playerStats: {
    loading: "Загрузка статистики...",
    notFound: "Статистика не найдена",
    rating: "Рейтинг:",
    games: "Игр:",
    wins: "Побед:",
    winRate: "Винрейт:",
    overview: "Обзор",
    gamesHistory: "История игр",
    partners: "Партнеры",
    gameStats: "Статистика игр",
    totalGames: "Всего игр:",
    victories: "Победы:",
    winPercent: "Процент побед:",
    totalPoints: "Всего очков:",
    pointsPerGame: "Очков за игру (в среднем):",
    indicators: "Показатели",
    currentRating: "Текущий рейтинг:",
    totalScored: "Всего набрано:",
    avgScorePerGame: "Средний счет за игру:",
    lastActivity: "Последняя активность:",
    compatibility: "Совместимость",
    uniqueTeammates: "Уникальных партнеров по команде:",
    uniqueOpponents: "Уникальных противников:",
    lastGames: "Последние игры",
    date: "Дата",
    team: "Команда",
    opponents: "Противник",
    score: "Счет",
    result: "Результат",
    victory: "победа",
    defeat: "поражение",
    points: "Очки",
    history: "История игр",
    historyNotFound: "История игр не найдена",
    teammates: "Партнеры по команде",
    teammatesNotFound: "Партнеры не найдены",
    opponents: "Противники",
    opponentsNotFound: "Противники не найдены",
  },

  // Управление данными
  dataManagement: {
    title: "Управление данными",
    exportData: "Экспорт данных",
    exportDescription: "Сохраните все данные турниров, историю и рейтинги игроков в файл JSON для резервного копирования или переноса на другое устройство.",
    exportButton: "Экспортировать данные",
    importData: "Импорт данных",
    importDescription: "Загрузите ранее экспортированный файл JSON для восстановления данных о турнирах, истории и рейтингах игроков.",
    importButton: "Импортировать данные",
    dataClear: "Очистка данных",
    clearDescription: "Удаление текущего турнира. Это действие нельзя отменить.",
    clearButton: "Очистить текущий турнир",
    clearConfirm: "Вы уверены? Это действие нельзя отменить.",
    exportSuccess: "Данные успешно экспортированы",
    exportError: "Произошла ошибка при экспорте данных",
    importSuccess: "Данные успешно импортированы",
    importError: "Произошла ошибка при импорте данных",
    fileError: "Произошла ошибка при обработке файла",
    readError: "Ошибка чтения файла",
  },

  // Уведомления
  notifications: {
    tournamentCreated: "Турнир создан",
    teamsFormedMessage: "Команды сформированы и расписание готово ({games} игр). Формат: {format}",
    newTournament: "Новый турнир",
    newTournamentMessage: "Прошлый турнир очищен, можно начинать новый.",
    gameStarted: "Игра начата",
    gameStartedMessage: "Раунд {round} начинается. Команда {team1} против {team2}",
    gameFinished: "Игра завершена",
    gameFinishedMessage: "Раунд {round} завершён со счётом {score1}:{score2}.",
    tournamentFinished: "Турнир завершен",
    tournamentFinishedMessage: "Все игры сыграны! Проверьте итоговую таблицу результатов.",
    settingsSaved: "Настройки сохранены",
    settingsSavedMessage: "Изменения настроек применены к турниру.",
    dataExport: "Экспорт данных",
    dataExportSuccess: "Данные успешно экспортированы в файл.",
    exportError: "Ошибка экспорта",
    exportErrorMessage: "Произошла ошибка при экспорте данных.",
    importError: "Ошибка импорта",
    fileNotSelected: "Файл не выбран.",
    dataImport: "Импорт данных",
    dataImportSuccess: "Данные успешно импортированы.",
    importError: "Ошибка импорта",
    importErrorMessage: "Ошибка при импорте данных.",
    formatError: "Файл содержит неверный формат данных.",
    readError: "Не удалось прочитать файл.",
  },

  // Сброс турнира
  resetTournament: {
    title: "Сбросить текущий турнир?",
    message: "У вас уже запущен турнир. Все данные будут потеряны! Вы уверены, что хотите сбросить его",
    andStartNew: "и начать новый",
    cancel: "Отмена",
    reset: "Сбросить турнир",
    resetAndStart: "Сбросить и начать новый",
  },

  // Правила
  rules: {
    title: "Правила турнира",
    basicPrinciples: "Основные принципы турнира",
    flexibility: "Гибкость формата:",
    flexibilityDesc: "Поддержка разных форматов команд — полноценные команды (6–7 человек), тройки или двойки.",
    randomization: "Рандомизация составов:",
    randomizationDesc: "Составы меняются перед каждым раундом для разнообразия и баланса.",
    fairness: "Справедливость:",
    fairnessDesc: "Равное игровое время для всех участников.",
    transparency: "Прозрачность:",
    transparencyDesc: "Доступная история результатов и статистика.",
    formats: "Форматы турнира",
    fullTeamsFormat: "Полноценные команды (8–14 участников):",
    fullTeamsDesc1: "Две команды по 6–7 человек",
    fullTeamsDesc2: "Игра до 25 очков с минимальной разницей в 2 очка",
    triplesFormat: "Формат троек (15 или 18 участников):",
    triplesDesc1: "5–6 троек (по 3 человека)",
    triplesDesc2: "Игра до 15 очков",
    triplesDesc3: "Одна тройка отдыхает в каждом раунде",
    doublesFormat: "Формат двоек (16–17 участников):",
    doublesDesc1: "8 двоек (по 2 человека)",
    doublesDesc2: "10-минутные матчи до 25 очков с разницей в 2 очка",
    doublesDesc3: "Две двойки отдыхают в каждом раунде",
    scoring: "Подсчёт очков",
    scoringDesc: "Очки начисляются по единой системе:",
    forWin: "3 очка: за победу",
    forLoseGood: "2 очка: за поражение, если команда набрала 10 или более очков",
    forLoseBad: "1 очко: за поражение, если команда набрала менее 10 очков",
    close: "Закрыть",
  },

  // Модальное окно импорта данных
  importModal: {
    title: "Импорт данных",
    selectFile: "Выберите файл JSON для импорта:",
    cancel: "Отмена",
    importing: "Импорт...",
    import: "Импортировать",
  },

  // Выбор режима команд
  teamMode: {
    selectMode: "Выбор режима создания команд",
    playersCount: "Количество игроков",
    description: "Выберите способ формирования команд для турнира",
    automatic: "Автоматический",
    manual: "Ручной",
    autoFeature1: "Быстрое создание команд",
    autoFeature2: "Балансировка по рейтингу",
    autoFeature3: "Оптимальное распределение",
    manualFeature1: "Полный контроль составов",
    manualFeature2: "Выбор партнеров",
    manualFeature3: "Учет личных предпочтений",
    autoDescription: "Команды будут созданы автоматически с учетом рейтингов игроков для максимальной сбалансированности.",
    manualDescription: "Вы сможете самостоятельно распределить игроков по командам, используя удобный интерфейс drag & drop.",
  },

  // Ручное создание команд
  manualTeam: {
    buildTeams: "Создание команд",
    instructions: "Инструкции",
    dragAndDrop: "Перетащите игроков между зонами или используйте кнопки для перемещения",
    autoDistribute: "Авто-распределение",
    clearAll: "Очистить все",
    unassigned: "Неназначенные",
    team1: "Команда 1",
    team2: "Команда 2",
    players: "игроков",
    dropPlayersHere: "Перетащите игроков сюда",
    allPlayersAssigned: "Все игроки распределены",
    moveToTeam1: "Переместить в команду 1",
    moveToTeam2: "Переместить в команду 2",
    moveToUnassigned: "Убрать из команды",
    teamStatus: "Статус команд",
    allPlayersAssignedStatus: "Все игроки распределены",
    bothTeamsHavePlayers: "Обе команды имеют игроков",
    createTeams: "Создать команды",
    teamFull: "{teamName} заполнена ({maxSize}/{maxSize}). Попробуйте другую команду.",
    teamFullSuggestion: "{teamName} заполнена! Попробуйте добавить игрока в {alternativeTeam}.",
    teamComplete: "Команда укомплектована",
    teamProgress: "Заполнено {progress}%",
  },

  // Смена составов
  teamComposition: {
    title: "Изменение состава команд",
    beforeSetDescription: "Настройте составы команд перед {set} сетом",
    shuffle: "Перемешать",
    swapTeams: "Поменять команды местами",
    status: "Статус",
    compositionChanged: "Состав команд изменен",
    noChanges: "Изменений нет",
    teamSizes: "Размеры команд",
    applyChanges: "Применить изменения",
    moveToTeam1: "Переместить в команду 1",
    moveToTeam2: "Переместить в команду 2",
  },
};